default:
  image: alpine:3.14

verify_merge:
  stage: .pre
  before_script:
    - apk add git
    - apk add python3 clang-extra-tools
  script:
    - export "PATH=$PATH:/usr/share/clang"
    - JIRA_ID=$($CI_PROJECT_DIR/tools/spdb_git_merge_check.sh "$CI_COMMIT_REF_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME")
    - JOB_NAME=$(echo "$CI_COMMIT_REF_NAME" | tr '/' '_')
    - echo "JIRA_ID=$JIRA_ID" >> merge.env
    - echo "JOB_NAME=$JOB_NAME" >> merge.env
  artifacts:
    reports:
      dotenv: merge.env
  only:
    - merge_requests

fuzzing:
  stage: test
  script:
    - echo "running fuzz"
  variables:
    GIT_STRATEGY: none
  only:
    - merge_requests
  dependencies:
    - verify_merge

bump_version:
  stage: deploy
  variables:
    VERSION_HEADER: $CI_PROJECT_DIR/speedb/version.h
  before_script:
    - apk add git
    - apk add python3
  script:
    - >
      $CI_PROJECT_DIR/tools/bump_version.py --version "$VERSION_HEADER"
      --target "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  only:
    - merge_requests
  dependencies:
    - verify_merge
    - fuzzing
